<?php
/**
 * PI Avatar Module.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Magento Team
 * that is bundled with this package of PI Infomatix Pvt. Ltd.
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * PI Support does not guarantee correct work of this package
 * on any other Magento edition except Magento COMMUNITY edition.
 * =================================================================
 */


/*
 * Template PI_Avatar_Header_Avatar 
 */
?>
<div class="avatar-block">


    <?php if ($this->getAvatar()): ?> 
        <?php echo $this->getAvatarHtml() ?>
    <?php endif ?> 

</div>
